# Generated by Django 3.2.6 on 2021-08-25 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zmogus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vardas', models.CharField(max_length=250)),
                ('last_login', models.DateField(default=datetime.date.today)),
                ('pora', models.CharField(max_length=250)),
                ('arPanaudotas', models.BooleanField(default=False)),
            ],
        ),
    ]
