# Generated by Django 3.2.6 on 2021-08-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zmogus',
            name='arPanaudotas',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='zmogus',
            name='pora',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
