# Generated by Django 3.2.6 on 2021-08-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210826_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zmogus',
            name='pora',
            field=models.CharField(blank=True, default='________', max_length=250),
        ),
    ]
