# Generated by Django 3.2.6 on 2021-08-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_zmogus_pora'),
    ]

    operations = [
        migrations.AddField(
            model_name='zmogus',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
