# Generated by Django 3.2.6 on 2021-08-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_zmogus_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebZinute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zinute', models.CharField(max_length=255)),
            ],
        ),
    ]
