# Generated by Django 3.2.6 on 2021-08-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_webzinute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webzinute',
            name='zinute',
            field=models.CharField(default='-\\_Žinutė_/-', max_length=255),
        ),
    ]
